:sectnums:
:chapter-label:

= 第３章 Swing

この章では、Swingというパッケージを使って、簡単なものを作っていきます。

== Swingとは

Javaで作成するプログラムをアプリケーションといいます。この中で、GUIアプリケーションを作るのに使われるパッケージ（ライブラリ）が、Swingです。
ちなみに、GUIとは、Graphical User Interfaceの略で、画面が出てくるアプリケーションのことです。

== Swing の基本スタイル

今回は、このテンプレートを使って、ゲームを作っていきたいと思います。

[source, java]
----
include::MyJPanel.java[lines=2..-1]
----

実行結果：

image::[CSSC2016]SwingSample1の実行結果.png[result1]

何もないウィンドウが表示されたと思います。Javaコースではこのウィンドウを使って、いろいろなアプリケーションを作っていくことになります。
mainメソッドの中に、`height`と`width`という変数があると思いますが、これの変数は画面の縦横の大きさが格納されています。
画面を大きさを変更したいときは、heightとwidthの値を変えてやれば、画面が大きくなったり小さくなったりします。


何もないと味気ないので、文字を表示するアプリケーションを作ってみましょう。「Hello World!」と表示するために、さっきのコードを少し変えましょう。
変えるのは、MyJPanelクラスの中の、while文の中にひとこと追加するだけです。

```java
while(true){
    g.drawString("Hello, world!" ,100,100); //追加！
    wg.drawImage(img, 0, 0, null);
}
```

最初に作ったウィンドウに、Hello, Worldという文字が表示されると思います。

=== drawString(string, x, y)
ここで、drawStringの定義を見てみましょう。

第１引数　: 表示する文字列
第２引数　：　表示するｘ座標
第３引数　：　表示するｙ座標

注意点として、ここでいうxとｙは、左から数えてxピクセル、上から数えてｙピクセルという意味です。Swingは基準点が左上なので、気をつけてください。
