= 第5章　簡単なゲームを作ってみよう

この章では、今までで学んだ知識を元に、簡単なゲームを作っていきたいと思います。

今回は、以下のような、主人公をキー操作で動かすようなプログラムを作ってみましょう。
image::img/sample-result[sample]

== 新しくプロジェクトを作る

この章でも、新しくプロジェクトを作ってゲームを作っていきましょう。
先ほどと同じように、新しいプロジェクトを作ります。次に、先ほど作ったプログラム（３つのJavaファイル）をこのプロジェクトにコピーします。

== 主人公を描いてみる

早速、主人公を描画してみましょう。画像を使って描いてもいいですが、とりあえず、四角形を主人公として描いてみます。

以下のコードを追加してみましょう。追加する場所は、４つ`if`文をかいたところの直後に追加してください。

```java
g.setColor(Color.GREEN);
g.fillRect(200,200,50,50);
```

このままでは、主人公が描画されただけで動きませので、次は主人公を動かすコードをかいてみましょう。

== 主人公を動かす

主人公を動かすにはどうすればいいでしょうか。ずばり、主人公を描画する位置を変えるしかないですね。
位置を変えるには、位置の情報を毎回どこかに保存して、随時それの情報を見ることができるような、”箱”のようなものが必要です。

その”箱”とは、*変数*のことです！
位置を格納する変数`x`と`ｙ`を宣言しましょう。

ここでは、`while`文の直前に宣言します。

```java
//while文の上に宣言
int x = 200;
int y = 200;
```

変数を宣言したところで、今度は変数を値を変えられるようにしましょう。例えば、`Up`キーを押すと、上に動く、みたいな感じです。

これをするために、`if`文の中をかきかえましょう。

[source, java]
----
include::code/MyJPanel.java[lines=20..31]
----

少し注意することとして、y座標は、上にいくほど値が減っていくので、`Up`キーが押された時は、yの値を減らしています。

最後に、主人公を描く位置を、xとｙにすればOKです。

```java
g.setColor(Color.GREEN);
g.fillRect(x,y,50,50);
```

これで無事、動くようになったはずです。
